name: Build addon archive
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    name: Build package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install gitman
        run: pipx install gitman
      - name: install dependencies
        run: gitman install
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "{VERSION}"
          include: LuaDatabase.toc
          replace: "${{ env.RELEASE_VERSION }}"
      - run: zip -r LuaDatabase.zip . --exclude="*.git*"
      - name: Create GitHub release
        uses: Roang-zero1/github-create-release-action@master
        with:
          version_regex: ^v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+
          #prerelease_regex: "^v0\\.[[:digit:]]+\\.[[:digit:]]+"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload artifact
        uses: fnkr/github-action-ghr@v1
        env:
          GHR_PATH: LuaDatabase.zip
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
